### ISSUE TITLE
Refined Relocation 2 not working on 1.16.1 Server

### ISSUE THREAD

**Issue by redbatz** [blay09/RefinedRelocation2#113]
### Summary
When trying to start a Minecraft 1.16.1 server with Refined Relocation 2 it fails with a **NoClassDefFoundError**, refering to the class `net/minecraft/tileentity/IChestLid`.

### Steps to reproduce
Install Minecraft Server of version 1.16.1 with Forge enabled, and add the _RefinedRelocation_1.16.1-8.0.0.jar_ to the _mods/_ directory.
Tried with both Forge version 32.0.57, which mod source code seems to be built against, and 32.0.98, latest version.

### Expected Results
Server to start properly with no errors, all functionality of the mod enabled in the game.

### Actual Results
Server fails to start due to critical error when trying to call the block registration of the mod with Forge.
The error is a **NoClassDefFoundError** for the class `net/minecraft/tileentity/IChestLid`. 
The Minecraft Client starts fine with the mod installed. 

Not a Minecraft Mod Developer, but `IChestLid` is an interface used by `SortingChestTileEntity`, and this interface is marked as `@OnlyIn(Dist.CLIENT)` in the Forge built mapped files. Could this cause the Server issues?
